### Primero importamos las librerias

In [2]:
import numpy as np
import pandas as pd
import zipfile

### Abrimos el archivo que se encuentra comprimido

In [3]:
with zipfile.ZipFile("all_pokemon.zip") as z:
    with z.open("all_pokemon.json") as f:
        data = pd.read_json(f)
data

,abilities,base_experience,cries,forms,game_indices,height,held_items,id,is_default,location_area_encounters,...,order,past_abilities,past_types,species,sprites,stats,types,weight,ranking,popularity
0,"[overgrow, chlorophyll]",64.0,{'latest': 'https://raw.githubusercontent.com/...,"[{'name': 'bulbasaur', 'url': 'https://pokeapi...","[{'game_index': 153, 'version': {'name': 'red'...",7.0,[],1.0,1.0,https://pokeapi.co/api/v2/pokemon/1/encounters,...,1.0,"[{'abilities': [{'ability': None, 'is_hidden':...",[],"{'name': 'bulbasaur', 'url': 'https://pokeapi....",{'back_default': 'https://raw.githubuserconten...,"{'hp': 45, 'attack': 49, 'defense': 49, 'speci...","{'type1': 'grass', 'type2': 'poison'}",69.0,28.0,72.8%
1,"[overgrow, chlorophyll]",142.0,{'latest': 'https://raw.githubusercontent.com/...,"[{'name': 'ivysaur', 'url': 'https://pokeapi.c...","[{'game_index': 9, 'version': {'name': 'red', ...",10.0,[],2.0,1.0,https://pokeapi.co/api/v2/pokemon/2/encounters,...,2.0,"[{'abilities': [{'ability': None, 'is_hidden':...",[],"{'name': 'ivysaur', 'url': 'https://pokeapi.co...",{'back_default': 'https://raw.githubuserconten...,"{'hp': 60, 'attack': 62, 'defense': 63, 'speci...","{'type1': 'grass', 'type2': 'poison'}",130.0,56.0,70.7%
2,[shed-skin],72.0,{'latest': 'https://raw.githubusercontent.com/...,"[{'name': 'metapod', 'url': 'https://pokeapi.c...","[{'game_index': 124, 'version': {'name': 'red'...",7.0,[],11.0,1.0,https://pokeapi.co/api/v2/pokemon/11/encounters,...,15.0,[],[],"{'name': 'metapod', 'url': 'https://pokeapi.co...",{'back_default': 'https://raw.githubuserconten...,"{'hp': 50, 'attack': 20, 'defense': 55, 'speci...","{'type1': 'bug', 'type2': None}",99.0,909.0,36%
3,"[soundproof, static, aftermath]",172.0,{'latest': 'https://raw.githubusercontent.com/...,"[{'name': 'electrode', 'url': 'https://pokeapi...","[{'game_index': 141, 'version': {'name': 'red'...",12.0,[],101.0,1.0,https://pokeapi.co/api/v2/pokemon/101/encounters,...,159.0,"[{'abilities': [{'ability': None, 'is_hidden':...",[],"{'name': 'electrode', 'url': 'https://pokeapi....",{'back_default': 'https://raw.githubuserconten...,"{'hp': 60, 'attack': 50, 'defense': 70, 'speci...","{'type1': 'electric', 'type2': None}",666.0,737.0,42.5%
4,[tablets-of-ruin],285.0,{'latest': 'https://raw.githubusercontent.com/...,"[{'name': 'wo-chien', 'url': 'https://pokeapi....",[],15.0,[],1001.0,1.0,https://pokeapi.co/api/v2/pokemon/1001/encounters,...,996.0,[],[],"{'name': 'wo-chien', 'url': 'https://pokeapi.c...","{'back_default': None, 'back_female': None, 'b...","{'hp': 85, 'attack': 85, 'defense': 100, 'spec...","{'type1': 'dark', 'type2': 'grass'}",742.0,669.0,44.6%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1024,"[thermal-exchange, ice-body]",64.0,{'latest': 'https://raw.githubusercontent.com/...,"[{'name': 'frigibax', 'url': 'https://pokeapi....",[],5.0,[],996.0,1.0,https://pokeapi.co/api/v2/pokemon/996/encounters,...,949.0,[],[],"{'name': 'frigibax', 'url': 'https://pokeapi.c...","{'back_default': None, 'back_female': None, 'b...","{'hp': 65, 'attack': 75, 'defense': 45, 'speci...","{'type1': 'dragon', 'type2': 'ice'}",170.0,1016.0,25.5%
1025,"[thermal-exchange, ice-body]",148.0,{'latest': 'https://raw.githubusercontent.com/...,"[{'name': 'arctibax', 'url': 'https://pokeapi....",[],8.0,[],997.0,1.0,https://pokeapi.co/api/v2/pokemon/997/encounters,...,950.0,[],[],"{'name': 'arctibax', 'url': 'https://pokeapi.c...","{'back_default': None, 'back_female': None, 'b...","{'hp': 90, 'attack': 95, 'defense': 66, 'speci...","{'type1': 'dragon', 'type2': 'ice'}",300.0,935.0,34.7%
1026,"[thermal-exchange, ice-body]",300.0,{'latest': 'https://raw.githubusercontent.com/...,"[{'name': 'baxcalibur', 'url': 'https://pokeap...",[],21.0,[],998.0,1.0,https://pokeapi.co/api/v2/pokemon/998/encounters,...,951.0,[],[],"{'name': 'baxcalibur', 'url': 'https://pokeapi...","{'back_default': None, 'back_female': None, 'b...","{'hp': 115, 'attack': 145, 'defense': 92, 'spe...","{'type1': 'dragon', 'type2': 'ice'}",2100.0,827.0,39.5%
1027,[rattled],60.0,{'latest': 'https://raw.githubusercontent.com/...,"[{'name': 'gimmighoul-chest', 'url': 'https://...",[],3.0,[],999.0,1.0,https://pokeapi.co/api/v2/pokemon/999/encounters,...,976.0,[],[],"{'name': 'gimmighoul', 'url': 'https://pokeapi...","{'back_default': None, 'back_female': None, 'b...","{'hp': 45, 'attack': 30, 'defense': 70, 'speci...","{'type1': 'ghost', 'type2': None}",50.0,726.0,42.8%
1028,[good-as-gold],275.0,{'latest': 'https://raw.githubusercontent.com/...,"[{'name': 'gholdengo', 'url': 'https://pokeapi...",[],12.0,[],1000.0,1.0,https://pokeapi.co/api/v2/pokemon/1000/encounters,...,977.0,[],[],"{'name': 'gholdengo', 'url': 'https://pokeapi....","{'back_default': None, 'back_female': None, 'b...","{'hp': 87, 'attack': 60, 'defense': 95, 'speci...","{'type1': 'steel', 'type2': 'ghost'}",300.0,815.0,39.9%

### Según los datos que nos pidan creamos el DataFrame

In [ ]:
"""df = data.copy()

# name desde species
df['name'] = pd.json_normalize(df['species'])['name']

# type1 y type2 desde types
types_df = pd.json_normalize(df['types'])
df[['type1','type2']] = types_df.reindex(columns=['type1','type2'])

# stats
stats_df = pd.json_normalize(df['stats'])
cols_stats = ['hp','attack','defense','special-attack','special-defense','speed']
df[cols_stats] = stats_df.reindex(columns=cols_stats)

# ordenar
df = df[['name','type1','type2','hp','attack','defense','special-attack','special-defense','speed']]
df"""

,name,type1,type2,hp,attack,defense,special-attack,special-defense,speed
0,bulbasaur,grass,poison,45.0,49.0,49.0,65.0,65.0,45.0
1,ivysaur,grass,poison,60.0,62.0,63.0,80.0,80.0,60.0
2,metapod,bug,None,50.0,20.0,55.0,25.0,25.0,30.0
3,electrode,electric,None,60.0,50.0,70.0,80.0,80.0,150.0
4,wo-chien,dark,grass,85.0,85.0,100.0,95.0,135.0,70.0
...,...,...,...,...,...,...,...,...,...
1024,frigibax,dragon,ice,65.0,75.0,45.0,35.0,45.0,55.0
1025,arctibax,dragon,ice,90.0,95.0,66.0,45.0,65.0,62.0
1026,baxcalibur,dragon,ice,115.0,145.0,92.0,75.0,86.0,87.0
1027,gimmighoul,ghost,None,45.0,30.0,70.0,75.0,70.0,10.0
1028,gholdengo,steel,ghost,87.0,60.0,95.0,133.0,91.0,84.0

In [4]:

types = pd.json_normalize(data['types'])
stats = pd.json_normalize(data['stats'])
species = pd.json_normalize(data['species'])

cols_stats = ['hp','special-attack','attack','defense','special-defense','speed']

df = pd.concat(
    [
        species[['name']],
        types.reindex(columns=['type1','type2']),
        stats.reindex(columns=cols_stats),
    ],
    axis=1
)[['name','type1','type2'] + cols_stats]

df

,name,type1,type2,hp,special-attack,attack,defense,special-defense,speed
0,bulbasaur,grass,poison,45.0,65.0,49.0,49.0,65.0,45.0
1,ivysaur,grass,poison,60.0,80.0,62.0,63.0,80.0,60.0
2,metapod,bug,None,50.0,25.0,20.0,55.0,25.0,30.0
3,electrode,electric,None,60.0,80.0,50.0,70.0,80.0,150.0
4,wo-chien,dark,grass,85.0,95.0,85.0,100.0,135.0,70.0
...,...,...,...,...,...,...,...,...,...
1024,frigibax,dragon,ice,65.0,35.0,75.0,45.0,45.0,55.0
1025,arctibax,dragon,ice,90.0,45.0,95.0,66.0,65.0,62.0
1026,baxcalibur,dragon,ice,115.0,75.0,145.0,92.0,86.0,87.0
1027,gimmighoul,ghost,None,45.0,75.0,30.0,70.0,70.0,10.0
1028,gholdengo,steel,ghost,87.0,133.0,60.0,95.0,91.0,84.0

### Mostrar los primeros n datos

In [5]:
df.head(20)

,name,type1,type2,hp,special-attack,attack,defense,special-defense,speed
0,bulbasaur,grass,poison,45.0,65.0,49.0,49.0,65.0,45.0
1,ivysaur,grass,poison,60.0,80.0,62.0,63.0,80.0,60.0
2,metapod,bug,None,50.0,25.0,20.0,55.0,25.0,30.0
3,electrode,electric,None,60.0,80.0,50.0,70.0,80.0,150.0
4,wo-chien,dark,grass,85.0,95.0,85.0,100.0,135.0,70.0
5,chien-pao,dark,ice,80.0,90.0,120.0,80.0,65.0,135.0
6,ting-lu,dark,ground,155.0,55.0,110.0,125.0,80.0,45.0
7,chi-yu,dark,fire,55.0,135.0,80.0,80.0,120.0,100.0
8,roaring-moon,dragon,dark,105.0,55.0,139.0,71.0,101.0,119.0
9,iron-valiant,fairy,fighting,74.0,120.0,130.0,90.0,60.0,116.0
10,koraidon,fighting,dragon,100.0,85.0,135.0,115.0,100.0,135.0
11,miraidon,electric,dragon,100.0,135.0,85.0,100.0,115.0,135.0
12,walking-wake,water,dragon,99.0,125.0,83.0,91.0,83.0,109.0
13,iron-leaves,grass,psychic,90.0,70.0,130.0,88.0,108.0,104.0
14,exeggcute,grass,psychic,60.0,60.0,40.0,80.0,45.0,40.0
15,dipplin,grass,dragon,80.0,95.0,80.0,110.0,80.0,40.0
16,poltchageist,grass,ghost,40.0,74.0,45.0,45.0,54.0,50.0
17,sinistcha,grass,ghost,71.0,121.0,60.0,106.0,80.0,70.0
18,okidogi,poison,fighting,88.0,58.0,128.0,115.0,86.0,80.0
19,munkidori,poison,psychic,88.0,130.0,75.0,66.0,90.0,106.0