# <img style="float: left; padding-right: 20px; width: 200px" src="https://raw.githubusercontent.com/raxlab/imt2200-data/main/media/logo.jpg">  IMT 2200 - Introducción a Ciencia de Datos
**Pontificia Universidad Católica de Chile**<br>
**Instituto de Ingeniería Matemática y Computacional**<br>
**Semestre 2025-S2**<br>
**Profesor:** Rodrigo A. Carrasco <br>

# <h1><center>Interrogación 1</center></h1>

## Instrucciones

* Esta parte de la Interrogación debe ser desarrollada completamente en lenguaje de programación Python en este Notebook de Jupyter.

* El desarrollo del Notebook debe ser claro y ordenado, incluyendo anotaciones (markdown) y comentarios que permitan seguir fácilmente el código y los pasos implementados, y siguiendo buenas prácticas de programación. <br>
* La entrega de la interrogación se realizará a través de Canvas en la actividad `I1 Desarrollo`.
* Esta Interrogación debe desarrollarse de manera totalmente *individual*, de acuerdo a lo establecido en la sección de Integridad Académica en el programa del curso.
* Está **estrictamente prohibido comunicarse con sus compañeros de curso, terceras personas o agentes de IA** durante el desarrollo de esta interrogación.
* Puede consultar los apuntes del curso de todo tipo.
* Habrá sólo dos instancias para hacer preguntas, una al inicio de la prueba y otra a los 30 minutos de avance.<br>


* Ud. dispone de 1 hora para desarrollar esta interrogación.
* Recuerde **guardar frecuentemente sus avances** para evitar pérdidas de trabajo o problemas de envío.<br>

*** 
## Parte 2: Trabajo de Desarrollo (60 min)

Esta parte de la Interrogación es un trabajo práctico con datos. En esta parte, cada pregunta debe ser respondida desarrollando un código por usted que le permita entregar una respuesta.

## 1. Extracción de datos de la red (6 pts.)

En esta sección, deberá escribir un código que le permita hacer una solicitud a una URL para obtener un archivo JSON.

Suponga que usted encuentra el siguiente endpoint en la documentación de una API:

```
URL = "www.example-api-url.com/LAT={latitude},LON={longitude},DATE={date (DD-MM-YYYY)}"
```

Complete la función `request_fnc` de modo que:
* Reciba como input (argumentos) los parámetros del endpoint y un nombre de archivo.
* Haga una solicitud a la URL.
* Guarde como JSON el contenido de la respuesta con el nombre del archivo dado.


**Solo escriba el código de la función sin llamarla, ya que está utilizando un URL de ejemplo.**

In [ ]:
import requests
import pandas as pd

def request_fnc(lat, lon, date, filename):
    dia = date.strftime("%D")
    mes = date.strftime("%m")
    año = date.strftime("%y")
    url = f"www.example-api-url.com/LAT={lat},LON={lon},DATE={dia}-{mes}-{año}"
    respuestas = []
    respuesta = requests.get(url, stream=True)

    if respuesta.status_code == 200 and respuesta.text.strip():
        data = respuesta.json()
        respuestas.extend(data)
    else:
        print("no hay datos para", {dia}-{mes}-{año})

    df = pd.DataFrame(respuestas)
    df.to_csv("respuestas.csv", index=False)
    return df

## 2. Lectura y creación de un DataFrame (6 pts.)

En la siguientes celdas (puede agregar celdas si lo necesita) escriba un código que lea el archivo `all_pokemon.json` que debió bajar a su computador antes de la prueba y lo deje en un DataFrame de pandas.

Cargue e inspeccione los índices del archivo. Luego, genere un único DataFrame que contenga las siguientes columnas:
```
["id", "name", "base_experience", "height", "weight", "is_default", "type1", "type2",
"hp","attack","defense","special-attack","special-defense","speed", "ranking", "popularity"]
```

Cuando corresponda, use métodos de aplanamiento (`json_normalize`). Puede crear múltiples DataFrames que le sean de utilidad en el proceso, pero debe obtener finalmente un solo DataFrame unificado con las columnas indicadas.

In [1]:
#type:ignore
import pandas as pd
import zipfile

with zipfile.ZipFile("all_pokemon.zip") as z:
    with z.open("all_pokemon.json") as f:
        data = pd.read_json(f)

df = data.copy()
df["name"] = pd.json_normalize(df["species"])["name"]

types_df = pd.json_normalize(df['types'])
df[['type1','type2']] = types_df.reindex(columns=['type1','type2'])

estadisticas = pd.json_normalize(df['stats'])
col_stats = ['hp','attack','defense','special-attack','special-defense','speed']
df[col_stats] = estadisticas.reindex(columns=col_stats)

df = df[['id','name','base_experience','height','weight',
        'is_default','type1','type2','hp','attack','defense',
        'special-attack','special-defense','speed','ranking','popularity']]
df

,id,name,base_experience,height,weight,is_default,type1,type2,hp,attack,defense,special-attack,special-defense,speed,ranking,popularity
0,1.0,bulbasaur,64.0,7.0,69.0,1.0,grass,poison,45.0,49.0,49.0,65.0,65.0,45.0,28.0,72.8%
1,2.0,ivysaur,142.0,10.0,130.0,1.0,grass,poison,60.0,62.0,63.0,80.0,80.0,60.0,56.0,70.7%
2,11.0,metapod,72.0,7.0,99.0,1.0,bug,None,50.0,20.0,55.0,25.0,25.0,30.0,909.0,36%
3,101.0,electrode,172.0,12.0,666.0,1.0,electric,None,60.0,50.0,70.0,80.0,80.0,150.0,737.0,42.5%
4,1001.0,wo-chien,285.0,15.0,742.0,1.0,dark,grass,85.0,85.0,100.0,95.0,135.0,70.0,669.0,44.6%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1024,996.0,frigibax,64.0,5.0,170.0,1.0,dragon,ice,65.0,75.0,45.0,35.0,45.0,55.0,1016.0,25.5%
1025,997.0,arctibax,148.0,8.0,300.0,1.0,dragon,ice,90.0,95.0,66.0,45.0,65.0,62.0,935.0,34.7%
1026,998.0,baxcalibur,300.0,21.0,2100.0,1.0,dragon,ice,115.0,145.0,92.0,75.0,86.0,87.0,827.0,39.5%
1027,999.0,gimmighoul,60.0,3.0,50.0,1.0,ghost,None,45.0,30.0,70.0,75.0,70.0,10.0,726.0,42.8%
1028,1000.0,gholdengo,275.0,12.0,300.0,1.0,steel,ghost,87.0,60.0,95.0,133.0,91.0,84.0,815.0,39.9%

## 3. Inspección de los datos

En esta sección, inspeccione el DataFrame generado y responda con texto y/o código según corresponda.

#### 3.1 Imprima una muestra de 5 filas al azar de su dataset (3 pts.)

In [2]:
df.head(5)

,id,name,base_experience,height,weight,is_default,type1,type2,hp,attack,defense,special-attack,special-defense,speed,ranking,popularity
0,1.0,bulbasaur,64.0,7.0,69.0,1.0,grass,poison,45.0,49.0,49.0,65.0,65.0,45.0,28.0,72.8%
1,2.0,ivysaur,142.0,10.0,130.0,1.0,grass,poison,60.0,62.0,63.0,80.0,80.0,60.0,56.0,70.7%
2,11.0,metapod,72.0,7.0,99.0,1.0,bug,None,50.0,20.0,55.0,25.0,25.0,30.0,909.0,36%
3,101.0,electrode,172.0,12.0,666.0,1.0,electric,None,60.0,50.0,70.0,80.0,80.0,150.0,737.0,42.5%
4,1001.0,wo-chien,285.0,15.0,742.0,1.0,dark,grass,85.0,85.0,100.0,95.0,135.0,70.0,669.0,44.6%

#### 3.2 Imprima un resumen de los estadísticos principales (cantidad, valor promedio, máximos y mínimos, etc) para todas las columnas numérticas de su dataset (3 pts.)

In [3]:
df[['id','base_experience', 'height','weight',
    'is_default','hp','attack','defense','special-attack',
    'special-defense','speed','popularity']].describe()

,id,base_experience,height,weight,is_default,hp,attack,defense,special-attack,special-defense,speed
count,1028.000000,1028.000000,1028.000000,1028.000000,1028.0,1028.00000,1028.000000,1028.000000,1028.000000,1028.000000,1028.000000
mean,512.979572,150.904669,12.105058,668.751946,1.0,70.18677,77.485409,72.495136,70.017510,70.176070,67.145914
std,295.623465,78.845397,12.466456,1211.192251,0.0,26.66066,29.786759,29.272766,29.646763,26.634442,28.712423
min,1.000000,36.000000,1.000000,1.000000,1.0,1.00000,5.000000,5.000000,10.000000,20.000000,5.000000
25%,257.750000,66.000000,5.000000,85.000000,1.0,50.00000,55.000000,50.000000,47.000000,50.000000,45.000000
50%,513.500000,158.000000,10.000000,280.000000,1.0,68.00000,75.000000,70.000000,65.000000,66.500000,65.000000
75%,768.250000,184.000000,15.000000,700.000000,1.0,85.00000,100.000000,90.000000,90.000000,85.250000,88.000000
max,1025.000000,608.000000,200.000000,9999.000000,1.0,255.00000,181.000000,230.000000,173.000000,230.000000,200.000000

#### 3.3 Imprima todos los valores de `type1` y `type2` que existen en su dataset. ¿Cuántos son? (3 pts.)

In [15]:
limpio1 = df["type1"].drop_duplicates(keep="first")
limpio2 = df["type2"].drop_duplicates(keep="first")

print(f"el dataset tiene {len(limpio1)} type1")
print(limpio1.head(20))
print(f"el dataset tiene {len(limpio2)} type2")
print(limpio2.head(20))

el dataset tiene 19 type1
0         grass
2           bug
3      electric
4          dark
8        dragon
9         fairy
10     fighting
12        water
18       poison
22        steel
24         fire
27         rock
29       normal
31       ground
51      psychic
53          ice
136       ghost
630      flying
779         NaN
Name: type1, dtype: object
el dataset tiene 20 type2
0        poison
2          None
4         grass
5           ice
6        ground
7          fire
8          dark
9      fighting
10       dragon
13      psychic
16        ghost
20        fairy
38       flying
39         rock
68        water
103    electric
143       steel
300         bug
658      normal
779         NaN
Name: type2, dtype: object

#### 3.4 Muestre los tipos de cada columna de su DataFrame (3 pts.)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1029 entries, 0 to 1028
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1028 non-null   float64
 1   name             1028 non-null   object
 2   base_experience  1028 non-null   float64
 3   height           1028 non-null   float64
 4   weight           1028 non-null   float64
 5   is_default       1028 non-null   float64
 6   type1            1028 non-null   object
 7   type2            526 non-null    object
 8   hp               1028 non-null   float64
 9   attack           1028 non-null   float64
 10  defense          1028 non-null   float64
 11  special-attack   1028 non-null   float64
 12  special-defense  1028 non-null   float64
 13  speed            1028 non-null   float64
 14  ranking          1028 non-null   float64
 15  popularity       1028 non-null   object
dtypes: float64(12), object(4)
memory usage: 136.7+ KB

#### 3.5 ¿Están correctos los tipos asignados por Pandas? ¿Cree que algunos podrían ser modificados? Justifique su respuesta. (5 pts.)

Creo que podrian modificarse los objetos para dejar en claro que son str y de esta manera ser mas representativos a lo que realmente son

Respuesta:

## 4. Limpieza del dataset

Para la siguiente sección, deberá crear un nuevo DataFrame **sin sobreescribir el anterior** llamado `clean_df`. Responda las preguntas con texto y/o código según corresponda.

In [ ]:
clean_df = df.copy

#### 4.1 ¿Existen filas con valores nulos en su DataFrame? Si es así, imprima cuáles filas contienen valores nulos. ¿Cuántas son? En caso contrario, escriba el código que le permite saber que no hay valores nulos. (4 pts.)

In [ ]:
vacios = clean_df.isnan()

AttributeError: 'function' object has no attribute 'isna'

#### 4.2 Según lo obtenido, elimine las filas que considere inválidas de `clean_df` y justifique porqué. Si no encontró ninguna, escriba el código que le permitiría eliminar filas nulas de `clean_df`. (4 pts.)

Respuesta:

In [ ]:
# Respuesta

#### 4.3 ¿Existen filas duplicadas en su DataFrame? Si es así, muestre cuáles son. Si no, escriba el código que le permite saberlo. (3 pts.)

In [ ]:
# Respuesta

#### 4.4 Elimine las filas duplicadas de `clean_df`, dejando únicamente el primer registro. Si no hay ninguna, escriba el código que le permitiría eliminar filas duplicadas de `clean_df`. (4 pts.)

In [ ]:
# Respuesta

#### 4.5 Acorde con lo que respondió en el item 3.5, aplique las transformaciones a los tipos a las columnas que consideró incorrectas. Imprima nuevamente los nuevos tipos de todas las columnas (5 pts.)

In [ ]:
# Respuesta

#### 4.6 ¿Hay alguna columna que podría eliminar de su dataset? Justifique su respuesta. Si considera que existe alguna, escriba y ejecute un código que elimine esta columna de `clean_df`. En caso contrario, escriba un código que elimine una columna cualquiera, pero no lo ejecute (3 pts.)

In [ ]:
# Respuesta

## 5. Análisis de datos

En esta sección, utilice el DataFrame procesado en la sección anterior, `clean_df`, para responder las siguientes preguntas con texto y/o código.

#### 5.1 ¿Cuántas combinaciones de tipos (`type1` y `type2`) existen en su dataset? ¿Cuál es la combinación más común? (4 pts.)

Considere las combinaciones "simétricas" como dos combinaciones diferentes. Por ejemplo,`type1 = bug` y `type2 = water` **no es lo mismo que** `type1 = water` y `type2 = bug`.

In [ ]:
# Respuesta

#### 5.2 ¿Existen pokemones para todas las posibles combinaciones de tipos? Si no es así, mencione un ejemplo de combinación que no existe en su dataset. Justifique su respuesta con código (3 pts.)

In [ ]:
# Respuesta

#### 5.3 Use la función entregada `get_column_avg_by_type()` y responda  (6 pts.):

* ¿Cuál es el tipo de pokemon más popular? Imprima el tipo y el valor promedio de popularidad.
* ¿Cuál es el tipo de pokemon más veloz? Imprima el tipo y el valor promedio de velocidad.
* ¿Cuál es el tipo de pokemon con mayor defensa? Imprima el tipo y el valor promedio de defensa.

In [ ]:
def get_column_avg_by_type(df: pd.DataFrame, column: str) -> pd.DataFrame:
    """
    (NO MODIFICAR)
    Retorna un DataFrame con el promedio de dicha columna agrupado por tipo de Pokémon.
    """
    all_types = df['type1'].unique()
    dfs_by_type = [clean_df[(clean_df['type1'] == t) | (clean_df['type2'] == t)] for t in all_types]
    avg_column = {t: df_t[column].mean() for t, df_t in zip(all_types, dfs_by_type)}
    return pd.DataFrame(avg_column.items(), columns=['type', f'avg_{column}'])

Respuesta:

In [ ]:
# Respuesta

#### 5.4 Muestre la relación entre la velocidad y defensa para pokemon de tipos "Electric" y "Rock" por separado. ¿Cómo se diferencian los stats mencionados en estos dos tipos? (5 pts.)

Para esto, realice un scatterplot que muestre estas dos variables solamente para estos dos tipos de pokemon. 
Recuerde colocarle título, nombre de ejes y etiquetas a su gráfico según corresponda. Además, recuerde que en el gráfico se debe poder diferenciar un tipo de otro. Puede utilizar la librería de visualización que le acomode.

In [ ]:
# Respuesta